# Generated by Django 2.1.1 on 2018-09-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_click_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_click_count', models.IntegerField(blank=True, null=True, verbose_name='用户点击图片总次数')),
                ('url_click_count', models.IntegerField(blank=True, null=True, verbose_name='用户点击链接总次数')),
            ],
            options={
                'verbose_name': '菜单点击量',
                'verbose_name_plural': '菜单点击量',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(blank=True, max_length=50, null=True, verbose_name='openid')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='昵称')),
                ('headimgurl', models.CharField(blank=True, max_length=50, null=True, verbose_name='头像')),
                ('sex', models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='国家')),
                ('province', models.CharField(blank=True, max_length=50, null=True, verbose_name='省份')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='城市')),
                ('subscribe_time', models.BigIntegerField(blank=True, null=True, verbose_name='关注时间')),
            ],
            options={
                'verbose_name': '已关注用户',
                'verbose_name_plural': '已关注用户',
            },
        ),
    ]
